name: Generate and Update Code

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_PAT }}

      - name: Install Gemini CLI
        run: npm install -g @google/gemini-cli

      - name: Generate updated code with Gemini
        id: generate-code
        run: |
          # Use Gemini CLI to generate or update content
          # This example generates a simple greeting and saves it to a file.
          # The '--yolo' flag bypasses prompts, which is essential for automation.
          gemini 'Strictly generate only the raw HTML content, beginning with `<!DOCTYPE html>` and ending with `</html>`. The output must not contain any prose, explanations, or comments. The HTML must produce an `index.html` file. Your entire response must be a single block of pure HTML code. Only output the HTML content itself, no comments, no explanations, nothing additional. Pick a random theme and choose one very interesting fact from it. The index.html should display that interesting fact. It should also choose the best matching color for the fact and use it as a background color for the website. It should also choose text color for the text to be clearly visible.' -o 'json' --yolo > output.json

          # Print the response for debugging purposes.
          cat output.json

          # Extract the content from the JSON output and save to a file.
          # You will need to parse the JSON output to get the generated code.
          jq -r '.candidates[0].output' output.json > index.html
          
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Commit and push changes
        run: |
          # Make sure the bot is configured correctly
          git config --local user.email "automatogreenhouse@gmail.com"
          git config --local user.name "Automato"
          
          # Stage the file.
          git add index.html
          
          # Check if there are changes to commit
          if ! git diff-index --quiet HEAD --; then
            git commit -m "feat: Automated commit from self-ai-update workflow"
            git push # Push the changes to the repository
          else
            echo "No changes to commit."
          fi
